# Generated by Django 2.1.4 on 2018-12-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='report_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org_structure.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='org_structure.Department'),
        ),
    ]
