# Generated by Django 2.1.4 on 2018-12-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0002_auto_20181215_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
