# Generated by Django 2.1.4 on 2018-12-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_structure', '0005_auto_20181215_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='start_date',
            new_name='join_date',
        ),
    ]
